// Generated by https://quicktype.io

// -> 1 ctr+shift+p
// -> 2 buscar Paste Json as Code
// -> 3 escribir el nombre

export interface Label {
  id: number;
  node_id: string;
  url: string;
  name: string;
  color: string;
  default: boolean;
  description?: string;
}
